#!/bin/sh
case "$1" in
        start|startup)
                /etc/init.d/ssh start
                ;;
        stop|shutdown)
                /etc/init.d/ssh stop
                ;;                              
        *)
                exit 0
                ;;              
esac

exit 0
